name: Build release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with javac
        run: javac -encoding windows-1252 ./*.java

      - name: Bundle release files in zip
        id: bundle
        run: |
          REV="$(git rev-parse --short "$GITHUB_SHA")"
          BUILD_ID="$(date '+%Y%m%dT%H%M%S')-$REV"
          BUNDLE_FILENAME="AddToDix-${BUILD_ID}.zip"
          find . -name '.??*' -prune -or \
            -type f -regextype egrep \
            -regex '.*\.(java|class|mf|md|txt|dix)$' -print \
            | zip -@ "${BUNDLE_FILNAME}"
          echo '::set-output name=BUILD_ID::'"${BUILD_ID}"
          echo '::set-output name=BUNDLE_FILENAME::'"${BUNDLE_FILENAME}"

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub release create \
            -m "Release $REV" \
            -t "$GITHUB_SHA" \
            -a "${{ steps.bundle.outputs.BUNDLE_FILENAME }}" \
            "release-${{ steps.bundle.outputs.BUILD_ID }}"
