name: Build release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with javac
        run: javac -encoding windows-1252 ./*.java

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REV="$(git rev-parse --short "$GITHUB_SHA")"
          hub release create -m "Revision $REV" \
            "$(date '+%Y%m%dT%H%M%S')-$REV"
