name: Build release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with javac
        run: javac -encoding windows-1252 ./*.java

      - name: Bundle release files in zip
        run: |
          find . -name '.??*' -prune -or \
            -type f -regextype egrep \
            -regex '.*\.(java|class|mf|md|txt|dix)$' -print \
            | zip -@ release.zip

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REV="$(git rev-parse --short "$GITHUB_SHA")"
          TAG="release-$(date '+%Y%m%dT%H%M%S')-$REV"
          hub release create \
            -m "Release $REV" \
            -t "$GITHUB_SHA" \
            -a "release-$REV.zip" \
            "$TAG"
